server:
  port: 8888 

spring:  
  application:  
    name: eureka-service
  security:
    user:
      name: admin
      password: admin123

eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  serviceUrl:
    defaultZone: http://localhost:${server.port}/eureka/