spring: 
  profiles: eurekaService1 
  server: 
  port: 8887 
  eureka: 
    instance: 
      hostname: peer2 
      prefer-ip-address: true 
      client: 
        serviceUrl: 
         defaultZone: http://peer1:8888/eureka/
