spring: 
  profiles: eurekaService1 
  server: 
  port: 8888 
  eureka: 
    instance: 
      hostname: peer1 
      prefer-ip-address: true 
    client: 
      serviceUrl: 
        defaultZone: http://peer2:8887/eureka/
