version: "1" 
services: 
  eurekaService1: # 默认情况下，其他服务可以使用服务名称连接到该服务。因此，对于peer2的节点，它需要连接http://peer1:8761/eureka/，因此需要配置该服务的名称是peer1。 
  image: eureka_center 
  networks: 
    - eureka-net 
  ports: 
    - "8888:8888" 
  environment: 
    - spring.profiles.active=eurekaService1 
  eurekaService2: 
  image: eureka_center 
  networks: 
    - eureka-net 
  ports: 
    - "8887:8887" 
  environment: 
    - spring.profiles.active=eurekaService2 