server:
  port: 8098
eureka:
  client:
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  
spring:
  redis:
    host: 192.168.1.113
    port: 6379
    timeout: 3600
    cluster:
      nodes: ${redisUrl}
    password: ${redisPassword}
    pool:
      max:
        active: 10
        idle: 8
        wait: -1
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    servlet:
      content-type: text/html
feign:
  hystrix:
    enabled: false
