server: 
  port: 80
  
spring: 
  application: 
    name: zuul-core-server
    
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://admin:admin@eureka1:8888/eureka/,http://admin:admin@eureka2:8888/eureka/
    healthcheck: 
      enabled: true
  instance:
    preferIpAddress: true
    ipAddress: 
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
hystrix: #hystrix配置
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000 
ribbon: 
  ReadTimeout: 60000
  ConnectTimeout: 60000
zuul: 
  sensitiveHeaders: "*"
  host:
    connectTimeoutMillis: 20000
    socketTimeoutMillis: 20000
  routes: 
    cgi: 
      path: /api/*
      serviceId: coreAPI-service
      stripPrefix: false
