server: 
  port: 80
  
spring: 
  #http: 
    #multipart: 
      #maxRequestSize: 800Mb
  servlet: 
    multipart:
      maxFileSize: 800Mb
      maxRequestSize: 800Mb
  application: 
    name: zuul-mainPage-server
    
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://admin:admin@eureka1:8888/eureka/,http://admin:admin@eureka2:8888/eureka/
    healthcheck: 
      enabled: true
    instance:
      preferIpAddress: true
      ipAddress: 
      leaseRenewalIntervalInSeconds: 10
      leaseExpirationDurationInSeconds: 30   
hystrix: #hystrix配置
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000  
ribbon: 
  ReadTimeout: 60000
  ConnectTimeout: 60000
  
zuul: 
  sensitiveHeaders: "*"
  routes: 
    file: 
      path: /**
      serviceId: PAN-PAGES
      stripPrefix: false