server: 
  port: 8081
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: ${databaseUrl}
    username: ${databaseUsername}
    password: ${databasePassword}
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    cluster: 
      nodes: ${redisUrl}
      timeout: 3600  
      maxAttempts: 5
  thymeleaf:
    mode: LEGACYHTML5
    content-type: text/html
    cache: false
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql
  reasonable: false
#xuyaorenzheng
eureka:
  client:
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    ipAddress: 
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
feign:
  hystrix:
    enabled: false
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 6000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1
