server:
  port: 8085
eureka:
  client:
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    ipAddress: 
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  
spring:
  redis:
    cluster: 
      nodes: ${redisUrl}
      timeout: 3600  
      maxAttempts: 5
  thymeleaf:
    mode: LEGACYHTML5
    content-type: text/html
    cache: false
feign:
  hystrix:
    enabled: false
