server: 
  port: 8095
  
spring: 
  application: 
    name: core-zuul
  servlet:
    multipart:
      maxFileSize: 800MB
      maxRequestSize: 800MB
    
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://admin:admin123@localhost:8888/eureka/
    healthcheck: 
      enabled: true
  instance: 
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
      
management: 
  security: false

    
ribbon: 
  ReadTimeout: 60000
  ConnectTimeout: 60000
  
zuul: 
  sensitiveHeaders:
  routes:
    core:
      path: /api/core/**
      serviceId: core-service
    edge:
      path: /api/edge/**
      serviceId: edge-service
    user:
      path: /api/user/**
      serviceId: user-service
    share:
      path: /api/share/**
      serviceId: share-service